services:
  geospatial-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geospatial-dashboard
    ports:
      - "80:80"
      - "443:443" # For HTTPS if needed
    restart: unless-stopped
    volumes:
      # Mount public directory for GeoJSON and GeoTIFF files
      - ./public:/usr/share/nginx/html/public:ro
      # Mount nginx config for custom configuration
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    # Resource limits for VM deployment
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"

networks:
  app-network:
    driver: bridge
